<?php
if ($change == "carte_A") {$select_A = "valign=\"top\"";} else {$select_A = "";}
if ($change == "carte_B") {$select_B = "valign=\"top\"";} else {$select_B = "";}
if ($change == "carte_C") {$select_C = "valign=\"top\"";} else {$select_C = "";}
if ($change == "carte_D") {$select_D = "valign=\"top\"";} else {$select_D = "";}
if ($change == "carte_E") {$select_E = "valign=\"top\"";} else {$select_E = "";}
?>
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center" height="260">
  <tr> 
          <td width="20%" <?php echo $select_A; ?>> 
            <div align="center"><a href="combat.php?change=carte_A&carte_A=<?php echo $carte_A; ?>&carte_B=<?php echo $carte_B; ?>&carte_C=<?php echo $carte_C; ?>&carte_D=<?php echo $carte_D; ?>&carte_E=<?php echo $carte_E; ?>&PV=<?php echo $PV; ?>&PV_adv=<?php echo $PV_adv; ?>&round=<?php echo $round; ?>&chevalier=<?php echo $chevalier; ?>&chevalier_adv=<?php echo $chevalier_adv; ?>&bonus_bc=<?php echo $bonus_bc; ?>&bonus_bc_adv=<?php echo $bonus_bc_adv; ?>&bonus_ao=<?php echo $bonus_ao; ?>&bonus_ao_adv=<?php echo $bonus_ao_adv; ?>&rao=<?php echo $rao; ?>&rao_adv=<?php echo $rao_adv; ?>&V=<?php echo $V; ?>&cs=<?php echo $special; ?>&cs_adv=<?php echo $special_adv; ?>"><img src="images/<?php echo $img_carte_A; ?>.png" width="169" height="225" border="0" style="filter:alpha(opacity=80); -moz-opacity: .4;" onMouseover="makevisible(this,0)" onMouseout="makevisible(this,1)" title="<?php echo $commentaire_carte_A; ?>" alt="<?php echo $commentaire_carte_A; ?>"  class="image"></a></div>
          </td>
          <td width="20%" <?php echo $select_B; ?>> 
            <div align="center"><a href="combat.php?change=carte_B&carte_A=<?php echo $carte_A; ?>&carte_B=<?php echo $carte_B; ?>&carte_C=<?php echo $carte_C; ?>&carte_D=<?php echo $carte_D; ?>&carte_E=<?php echo $carte_E; ?>&PV=<?php echo $PV; ?>&PV_adv=<?php echo $PV_adv; ?>&round=<?php echo $round; ?>&chevalier=<?php echo $chevalier; ?>&chevalier_adv=<?php echo $chevalier_adv; ?>&bonus_bc=<?php echo $bonus_bc; ?>&bonus_bc_adv=<?php echo $bonus_bc_adv; ?>&bonus_ao=<?php echo $bonus_ao; ?>&bonus_ao_adv=<?php echo $bonus_ao_adv; ?>&rao=<?php echo $rao; ?>&rao_adv=<?php echo $rao_adv; ?>&V=<?php echo $V; ?>&cs=<?php echo $special; ?>&cs_adv=<?php echo $special_adv; ?>"><img src="images/<?php echo $img_carte_B; ?>.png" width="169" height="225" border="0" style="filter:alpha(opacity=80); -moz-opacity: .4;" onMouseover="makevisible(this,0)" onMouseout="makevisible(this,1)" title="<?php echo $commentaire_carte_B; ?>" alt="<?php echo $commentaire_carte_B; ?>"  class="image"></a></div>
          </td>
          <td width="20%" <?php echo $select_C; ?>> 
            <div align="center"><a href="combat.php?change=carte_C&carte_A=<?php echo $carte_A; ?>&carte_B=<?php echo $carte_B; ?>&carte_C=<?php echo $carte_C; ?>&carte_D=<?php echo $carte_D; ?>&carte_E=<?php echo $carte_E; ?>&PV=<?php echo $PV; ?>&PV_adv=<?php echo $PV_adv; ?>&round=<?php echo $round; ?>&chevalier=<?php echo $chevalier; ?>&chevalier_adv=<?php echo $chevalier_adv; ?>&bonus_bc=<?php echo $bonus_bc; ?>&bonus_bc_adv=<?php echo $bonus_bc_adv; ?>&bonus_ao=<?php echo $bonus_ao; ?>&bonus_ao_adv=<?php echo $bonus_ao_adv; ?>&rao=<?php echo $rao; ?>&rao_adv=<?php echo $rao_adv; ?>&V=<?php echo $V; ?>&cs=<?php echo $special; ?>&cs_adv=<?php echo $special_adv; ?>"><img src="images/<?php echo $img_carte_C; ?>.png" width="169" height="225" border="0" style="filter:alpha(opacity=80); -moz-opacity: .4;" onMouseover="makevisible(this,0)" onMouseout="makevisible(this,1)" title="<?php echo $commentaire_carte_C; ?>" alt="<?php echo $commentaire_carte_C; ?>"  class="image"></a></div>
          </td>
          <td width="20%" <?php echo $select_D; ?>> 
            <div align="center"><a href="combat.php?change=carte_D&carte_A=<?php echo $carte_A; ?>&carte_B=<?php echo $carte_B; ?>&carte_C=<?php echo $carte_C; ?>&carte_D=<?php echo $carte_D; ?>&carte_E=<?php echo $carte_E; ?>&PV=<?php echo $PV; ?>&PV_adv=<?php echo $PV_adv; ?>&round=<?php echo $round; ?>&chevalier=<?php echo $chevalier; ?>&chevalier_adv=<?php echo $chevalier_adv; ?>&bonus_bc=<?php echo $bonus_bc; ?>&bonus_bc_adv=<?php echo $bonus_bc_adv; ?>&bonus_ao=<?php echo $bonus_ao; ?>&bonus_ao_adv=<?php echo $bonus_ao_adv; ?>&rao=<?php echo $rao; ?>&rao_adv=<?php echo $rao_adv; ?>&V=<?php echo $V; ?>&cs=<?php echo $special; ?>&cs_adv=<?php echo $special_adv; ?>"><img src="images/<?php echo $img_carte_D; ?>.png" width="169" height="225" border="0" style="filter:alpha(opacity=80); -moz-opacity: .4;" onMouseover="makevisible(this,0)" onMouseout="makevisible(this,1)" title="<?php echo $commentaire_carte_D; ?>" alt="<?php echo $commentaire_carte_D; ?>" class="image"></a></div>
          </td>         
    <td width="20%" <?php echo $select_E; ?>> 
      <div align="center"><a href="combat.php?change=carte_E&carte_A=<?php echo $carte_A; ?>&carte_B=<?php echo $carte_B; ?>&carte_C=<?php echo $carte_C; ?>&carte_D=<?php echo $carte_D; ?>&carte_E=<?php echo $carte_E; ?>&PV=<?php echo $PV; ?>&PV_adv=<?php echo $PV_adv; ?>&round=<?php echo $round; ?>&chevalier=<?php echo $chevalier; ?>&chevalier_adv=<?php echo $chevalier_adv; ?>&bonus_bc=<?php echo $bonus_bc; ?>&bonus_bc_adv=<?php echo $bonus_bc_adv; ?>&bonus_ao=<?php echo $bonus_ao; ?>&bonus_ao_adv=<?php echo $bonus_ao_adv; ?>&rao=<?php echo $rao; ?>&rao_adv=<?php echo $rao_adv; ?>&V=<?php echo $V; ?>&cs=<?php echo $special; ?>&cs_adv=<?php echo $special_adv; ?>"><img src="images/<?php echo $img_carte_E; ?>.png" width="169" height="225" border="0" style="filter:alpha(opacity=80); -moz-opacity: .4;" onMouseover="makevisible(this,0)" onMouseout="makevisible(this,1)" title="<?php echo $commentaire_carte_E; ?>" alt="<?php echo $commentaire_carte_E; ?>" class="image"></a></div>
          </td>
        </tr>
      </table>
    